export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_AUTH_FAILURE: "LOGIN_AUTH_FAILURE",

    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",

    OTP_REQUEST: "OTP_REQUEST",
    OTP_SUCCESS: "OTP_SUCCESS",
    OTP_FAILURE: "OTP_FAILURE",

    CHANGE_EMAIL_REQUEST: "CHANGE_EMAIL_REQUEST",
    CHANGE_EMAIL_SUCCESS: "CHANGE_EMAIL_SUCCESS",
    CHANGE_EMAIL_FAILURE: "CHANGE_EMAIL_FAILURE",

    EMAIL_OTP_REQUEST: "EMAIL_OTP_REQUEST",
    EMAIL_OTP_SUCCESS: "EMAIL_OTP_SUCCESS",
    EMAIL_OTP_FAILURE: "EMAIL_OTP_FAILURE",

    UPDATE_REQUEST: "UPDATE_REQUEST",
    UPDATE_SUCCESS: "UPDATE_SUCCESS",
    UPDATE_FAILURE: "UPDATE_FAILURE",

    UPDATE_PASSWORD_REQUEST: "UPDATE_PASSWORD_REQUEST",
    UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORDSUCCESS",
    UPDATE_PASSWORD_FAILURE: "UPDATE_PASSWORD_FAILURE",
  };

  export const contactConstants = {
    CONTACT_US_REQUEST: "CONTACT_US_REQUEST",
    CONTACT_US_SUCCESS: "CONTACT_US_SUCCESS",
    CONTACT_US_FAILURE: "CONTACT_US_FAILURE",
  };
  
  export const historyConstants = {
    HISTORY_REQUEST: "HISTORY_REQUEST",
    HISTORY_SUCCESS: "HISTORY_SUCCESS",
    HISTORY_FAILURE: "HISTORY_FAILURE",
  };
  