export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_AUTH_FAILURE: "LOGIN_AUTH_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  OTP_REQUEST: "OTP_REQUEST",
  OTP_SUCCESS: "OTP_SUCCESS",
  OTP_FAILURE: "OTP_FAILURE",

  CHANGE_EMAIL_REQUEST: "CHANGE_EMAIL_REQUEST",
  CHANGE_EMAIL_SUCCESS: "CHANGE_EMAIL_SUCCESS",
  CHANGE_EMAIL_FAILURE: "CHANGE_EMAIL_FAILURE",

  EMAIL_OTP_REQUEST: "EMAIL_OTP_REQUEST",
  EMAIL_OTP_SUCCESS: "EMAIL_OTP_SUCCESS",
  EMAIL_OTP_FAILURE: "EMAIL_OTP_FAILURE",

  UPDATE_REQUEST: "UPDATE_REQUEST",
  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  UPDATE_FAILURE: "UPDATE_FAILURE",

  UPDATE_PASSWORD_REQUEST: "UPDATE_PASSWORD_REQUEST",
  UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
  UPDATE_PASSWORD_FAILURE: "UPDATE_PASSWORD_FAILURE",

  RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",

  OTP_RESEND_REQUEST: "OTP_RESEND_REQUEST",
  OTP_RESEND_SUCCESS: "OTP_RESEND_SUCCESS",
  OTP_RESEND_FAILED: "OTP_RESEND_FAILED",
  OTP_RESEND_FAILURE: "OTP_RESEND_FAILURE",

  OTP_OPEN: "OTP_OPEN",
  OTP_CLOSE: "OTP_CLOSE",
};

export const contactConstants = {
  CONTACT_US_REQUEST: "CONTACT_US_REQUEST",
  CONTACT_US_SUCCESS: "CONTACT_US_SUCCESS",
  CONTACT_US_FAILURE: "CONTACT_US_FAILURE",
};

export const historyConstants = {
  HISTORY_REQUEST: "HISTORY_REQUEST",
  HISTORY_SUCCESS: "HISTORY_SUCCESS",
  HISTORY_FAILURE: "HISTORY_FAILURE",
};

export const prayerConstants = {
  PRAYER_REQUEST: "PRAYER_REQUEST",
  PRAYER_SUCCESS: "PRAYER_SUCCESS",
  PRAYER_FAILURE: "PRAYER_FAILURE",

  PAYMENT_REQUEST: "PAYMENT_REQUEST",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILURE: "PAYMENT_FAILURE",

  COUPON_REQUEST: "COUPON_REQUEST",
  COUPON_SUCCESS: "COUPON_SUCCESS",
  COUPON_FAILURE: "COUPON_FAILURE",
};

export const modalConstants = {
  GUEST_SUCCESS: "GUEST_SUCCESS",
  GUEST_MODAL_SUCCESS: "GUEST_MODAL_SUCCESS",
  USER_RECITE_SUCCESS: "USER_RECITE_SUCCESS"
};
